# Generated by Codex on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('SUCCESS', 'Successful login'),
                    ('AI_BLOCKED', 'AI blocked login'),
                    ('FAILED', 'Failed login'),
                    ('TEMP_BLOCKED', 'Temporary blocked login'),
                ],
                default='SUCCESS',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
